### ISSUE TITLE
Make Jellyfin get the absolute order from the tvdb API

### ISSUE THREAD

**Issue by Arlind-dev** [jellyfin/jellyfin-plugin-tvdb#101] opened 2023-10-20 10:55 UTC
I have tried doing that by using the Season ID of the absolute order but with no success, is there a limitation I am not familiar with?
Tried with https://thetvdb.com/series/one-piece/

**Comment by daynyxx** [comment] 2023-11-02 17:43
This would be an awesome feature. The [monogotari series](https://thetvdb.com/series/monogatari#seasons) being able to choose between aired order vs dvd vs absolute would be helpful.

**Comment by ttkjk** [comment] 2024-01-27 04:49
Yes,I think this feature it's necessary.

> This would be an awesome feature. For example, the [monogotari series](https://thetvdb.com/series/monogatari#seasons) being able to choose between aired order vs dvd vs absolute would be helpful.

**Comment by ChildishhAlbino** [comment] 2024-05-21 04:45
Hi - adding to this issue, I would also like the ability to fetch the DVD order. I am loading the blu ray version of Avatar - The Last Airbender to my Jellyfin server and noticing two things:
1. This plugin is NOT respecting the collections choice of series ordering, despite the information existing on TVDB
2. I can't use TMDB as a fallback as they do not have the correct ordering on their service.

**Comment by ChildishhAlbino** [comment] 2024-05-21 05:36
@scampower3 just bringing this to your attention as I've seen your commits change stuff I believe is related to this and just wanted to know if this is a recent occurrence.

I know from my anecdotal experience this was working in V10 of this plugin and seems to have broken in V11. 

If you want me to raise a separate issue for this as this one has gotten quite old/stale - I can.

**Comment by scampower3** [comment] 2024-05-21 05:38
Hello, this is a know issue.

Should be fixed with https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/143

**Comment by scampower3** [comment] 2024-05-21 06:14
The clear plugin cache + identify workaround should work. But, it might reorder the episodes.

Alternatively, you can test this https://github.com/scampower3/jellyfin-plugin-tvdb/releases/tag/test but this is 2 commits off from https://github.com/scampower3/jellyfin-plugin-tvdb/tree/restrict-some-data

**Comment by ChildishhAlbino** [comment] 2024-05-21 06:16
Yeah I'm hoping it will re-order the episodes - or in my case, correctly order them.

I'll check both of those out thanks @scampower3

**Comment by scampower3** [comment] 2024-05-21 06:29
@ChildishhAlbino I added an updated release here: https://github.com/scampower3/jellyfin-plugin-tvdb/releases/tag/test2

**Comment by ChildishhAlbino** [comment] 2024-05-21 06:56
hey @scampower3  I might still raise a separate issue because whilst that fix did actually grab the correct episode title and details for the variant episodes - it is marking them as `specials` instead of episodes in the season.

It is also incorrect labelling the episodes after the specials with their aired order numbering/titles the succeed the places where the specials are located.

A few examples and I'll let you tell me if this is expected behaviour or not (i don't presume so)

## Season 2 episode 12 (dvd order)
TVDB
<img width="676" alt="image" src="https://github.com/jellyfin/jellyfin-plugin-tvdb/assets/36402974/1c8733be-5e8a-4920-b82f-5601c1b0fa78">
JF
<img width="1549" alt="image" src="https://github.com/jellyfin/jellyfin-plugin-tvdb/assets/36402974/87c95a3d-3a19-4923-a429-ffc50f469eb0">

## Season 2 Episode 13
TVDB
<img width="768" alt="image" src="https://github.com/jellyfin/jellyfin-plugin-tvdb/assets/36402974/2128d59a-b208-429b-a392-27a32461d86b">
JF
<img width="1522" alt="image" src="https://github.com/jellyfin/jellyfin-plugin-tvdb/assets/36402974/ef6ca3d0-bb7f-4293-b618-934801578cb4">

**Comment by scampower3** [comment] 2024-05-21 07:32
The plugin depends on the season and episode numbers that Jellyfin provides. It shouldn't modify the season and episode numbering. 

Can you send me the steps that caused this issue to occur?

**Comment by ChildishhAlbino** [comment] 2024-05-21 07:41
Ok - maybe it is an issue with Jellyfin itself and not the plugin - although the files are labelled with the correct episode number in their filename. 

1. Install the test version of the plugin manually using 
2. Purge the plugin cache and set the show order to DVD order
3. Identify the show again as "Avatar - The Last Airbender" from TVDB
4. Check the episode titles in Season 2 (the first season where a difference from Aired Order and DVD order occurs)

**Comment by scampower3** [comment] 2024-05-21 07:45
When you set the show to the display order, Jellyfin will automatically run the full refresh, no need to do the identify again.

**Comment by ChildishhAlbino** [comment] 2024-05-21 07:58
Can do - I'll report back.

**Comment by ChildishhAlbino** [comment] 2024-05-21 08:49
Ok @scampower3 - even disabling all the other metadata plugins - I can't get this to work properly. I tested the plugin using "Dragon Ball Z Kai" which has a similar difference between Aired Order and DVD Order (best I can do) and it seemed to work fine. 

It is odd to me because the plugin is finding the correct TVDB id for each of the episodes but it using the season/episode number from the "Aired Order" and not from the "DVD Order" and that causes it to search for the wrong metadata in the DVD order.

Is there a better forum to discuss this issue in real time? I don't understand where JF is getting the metadata from if not from this plugin.

**Comment by scampower3** [comment] 2024-05-21 08:56
Can pm on discord scampower4

**Closed** 2024-05-22 17:21 UTC
